import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{io}from'socket.io-client';import'./style.css';
const API=import.meta.env.VITE_API_URL??'http://localhost:3000/api';
type Event={id:string;title:string;genre:string;city:string;startsAt:string};
function App(){const[events,setEvents]=useState<Event[]>([]),[q,setQ]=useState(''),[page,setPage]=useState('events'),[notice,setNotice]=useState('');const[token,setToken]=useState(localStorage.token??'');
useEffect(()=>{fetch(`${API}/events?q=${encodeURIComponent(q)}`).then(r=>r.json()).then(setEvents).catch(()=>setEvents([]))},[q]);
useEffect(()=>{const s=io(import.meta.env.VITE_WS_URL??'http://localhost:3000');['payment.succeeded','payment.failed','ticket.issued','seat.status.changed'].forEach(e=>s.on(e,()=>setNotice(e)));return()=>{s.close()}},[]);
async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch(`${API}/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});const x=await r.json();localStorage.token=x.accessToken;setToken(x.accessToken);setPage('events')}
return <><header><b>SeatFair</b><nav>{['events','seat map','checkout','my ticket','admin'].map(x=><button onClick={()=>setPage(x)}>{x}</button>)}</nav></header><main>{notice&&<aside>Live update: {notice}</aside>}
{!token||page==='login'?<section><h1>Welcome back</h1><form onSubmit={login}><input name="email" type="email" placeholder="Email"/><input name="password" type="password" placeholder="Password"/><button>Login</button></form><p>New customers can register through the API demo or registration endpoint.</p></section>:page==='events'?<section><h1>Discover live events</h1><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by title"/><div className="grid">{events.map(e=><article><span>{e.genre}</span><h2>{e.title}</h2><p>{e.city} · {new Date(e.startsAt).toLocaleString()}</p><button onClick={()=>setPage('seat map')}>Choose seats</button></article>)}</div></section>:page==='seat map'?<section><h1>Choose your seats</h1><div className="stage">STAGE</div><div className="seats">{Array.from({length:48},(_,i)=><button className="seat" aria-label={`Seat ${i+1}`}>{i+1}</button>)}</div><button onClick={()=>setPage('checkout')}>Reserve selected seats</button></section>:page==='checkout'?<section><h1>Checkout</h1><p>Your lock remains active for 10:00 minutes.</p><button>Simulate successful payment</button><button>Simulate failure</button></section>:page==='admin'?<section><h1>Organizer dashboard</h1><div className="grid"><article><h2>Venues</h2><button>Create venue</button></article><article><h2>Events</h2><button>Create & publish</button></article><article><h2>Sales</h2><strong>Live analytics</strong></article></div></section>:<section><h1>Ticket result</h1><div className="ticket"><div className="qr">QR</div><h2>Admission token</h2><p>Verify a ticket using its secure token.</p></div></section>}</main></>}
createRoot(document.getElementById('root')!).render(<App/>);
